### ISSUE TITLE
How to render in an ASP Core Razor View 

### ISSUE THREAD

**Issue by papyr** [Gabi1M/DrivingAssistant#3]
Hello I was trying to do a taxi dispatch/truck assistant with a web view, can you please help witha sample view.

thanks

**Comment by Gabi1M** [comment]
In my case, the video rendering was done in the Android application, fed by a stream provided by the ASP.Net backend. I suppose you can use the same stream to render it on a web page, but I can't give you an example as I'm not a front-end web developer. :)

**Comment by papyr** [comment]
Thanks for that, what format is the stream can you point to the API let me toy around with it and see if I can share an update here

**Comment by Gabi1M** [comment]
This is the method from the api that retrieves the stream. I simply open the file and use the filestream.

https://github.com/Gabi1M/DrivingAssistant/blob/902afec829f628ad9af6e980698d44a8053ae94c/DrivingAssistant/DrivingAssistant.WebServer/Controllers/VideoController.cs#L115

And this is where i use it in the Android app. I just pass the URI to the MediaController instance and it does the rest by itself.
Probably you can get the response stream from the HTTP request, apply what operations you might need, and use it.

https://github.com/Gabi1M/DrivingAssistant/blob/902afec829f628ad9af6e980698d44a8053ae94c/DrivingAssistant/DrivingAssistant.AndroidApp/Activities/Video/VideoActivityView.cs#L50
